OPSEXP-1833 Deploy on nexus
Alfresco/imagemagick-build pull request #24
Opened 2022-11-14 15:16 UTC by slohe1

OPSEXP-1833

2022-11-14 15:41 UTC, alxgomz requested changes

2022-11-14 15:41 UTC, alxgomz commented on .github/workflows/build.yml
> +          echo "release=$(cat ./.github/actions/release-version)" >> $GITHUB_OUTPUT
I did not realize we had such generic variable names.
Please use something more precise like `imagemagick_version` & `imagemagick_release` that is also more consistent with the filenames

2022-11-14 15:41 UTC, alxgomz commented on .github/workflows/build.yml
> +          echo "release=$(cat ./.github/actions/release-version)" >> $GITHUB_OUTPUT
same as above

2022-11-14 15:41 UTC, alxgomz commented on .github/workflows/build.yml
> +          echo "release=$(cat ./.github/actions/release-version)" >> $GITHUB_OUTPUT
same as above

2022-11-14 15:41 UTC, alxgomz commented on .github/workflows/build.yml
> +          echo "release=$(cat ./.github/actions/release-version)" >> $GITHUB_OUTPUT
same as above

2022-11-14 15:41 UTC, alxgomz commented on .github/workflows/build.yml
> +          echo "release=$(cat ./.github/actions/release-version)" >> $GITHUB_OUTPUT
same as above

2022-11-14 16:47 UTC, gionn commented on .github/workflows/build.yml
>        - name: Set imagemagick version
```suggestion
      - name: Set build variables
```

or something similar

2022-11-15 09:00 UTC, gionn commented on .github/workflows/build.yml
> +          version: ${{ steps.build.outputs.built-version }}-${{ steps.imagemagick.outputs.imagemagick_release }}-ci
I think it's better to have -ci as a prefix to always have it in the same place, swap them:

```
${{ steps.build.outputs.built-version }}-ci-${{ steps.imagemagick.outputs.imagemagick_release }}
```

2022-11-15 11:21 UTC, alxgomz approved these changes

2022-11-16 03:31 UTC, merged