OPSEXP-1928 Automate rpm Requires of the imagemagick packages
Alfresco/imagemagick-build pull request #35
Opened 2023-01-13 05:58 UTC by slohe1

OPSEXP-1928

2023-01-13 09:33 UTC, alxgomz requested changes
:) nice try
Can you instead investigate a method that's not bound to specific version. We want to avoid having to maintain such if statements.

2023-01-19 09:11 UTC, gionn reviewed
don't want to add more entropy here, but I would:

* have sh fragments for each version instead of rpm_cap**.txt (e.g. override-7.0.10-59.sh)
* in the entrypoint.sh, add a `source override-$VERSION.sh` to execute that override before the `./configure`

2023-01-20 11:32 UTC, alxgomz submitted a review, later dismissed
small formatting issue

2023-01-20 11:32 UTC, alxgomz commented on .github/actions/rockylinux-build/entrypoint.sh
> + cd ImageMagick && \
please pay attention to formatting

```suggestion
cd ImageMagick && \
```

2023-01-20 13:13 UTC, alxgomz approved these changes

2023-01-20 13:16 UTC, merged