OPSEXP-2333 Fix the issue with the ImageMagick packages for RockyLinux 9
Alfresco/imagemagick-build pull request #69
Opened 2023-10-10 06:44 UTC by slohe1

OPSEXP-2333

2023-10-10 08:29 UTC, alxgomz requested changes
Ideally we should test `.deb`as well. If you feel like it's fast enough please implement, otherwise create a new JIRA for that

2023-10-10 08:29 UTC, alxgomz commented on .github/workflows/build.yml
> +  test_and_run_command:
this job is a condition to deploy top nexus. We don't want to deploy on nexus if the tests fail

2023-10-10 08:29 UTC, alxgomz commented on rpms/after-checkout-rockylinux9-7.1.0-16.sh
That's ^pretty difficult to read :)
Can you explain what was the problem?

2023-10-10 10:09 UTC, gionn requested changes

2023-10-11 07:35 UTC, gionn requested changes

2023-10-11 07:35 UTC, gionn commented on .github/workflows/build.yml
> +  Build:
lowercase

2023-10-11 07:35 UTC, gionn commented on .github/workflows/build.yml
> +  Test:
lowercase

2023-10-11 07:35 UTC, gionn commented on .github/workflows/build.yml
> +    needs: [configure,Build]
alway use the multiline notation for readability

2023-10-11 07:35 UTC, gionn commented on config.json
move it under rpms folder to make it clear that is rpm-only

2023-10-11 07:35 UTC, gionn commented on .github/workflows/build.yml
>        - name: Deploy to nexus
at this point I prefer having a dedicated deploy job - feels a bit cheating that we are doing deploy at the end of a job which is called 'test'

2023-10-11 20:26 UTC, closed without merging